/* translates the outcodes generated by the keyboard driver into commands for the snake to move
Parameters:
	clk: the clock that drives the sequential logic in the system
	reset: resets the current state that the keyboard is translating to idle
	valid:
	makeBreak: determines whether the inputted outCode is a make code, indicating that a button had just been pressed
	outCode: the input outcode from the keyboard driver
	directionCommand: an output of the translated input key presses, utilizes WASD scheme
*/
module keyboardTranslate(clk, reset, valid, makeBreak, outCode, directionCommand);
	input logic clk, reset, valid, makeBreak;
	input logic [7:0] outCode;
	output logic [3:0] directionCommand;
	
	enum {IDLE, LP, RP, UP, DP} ps, ns;
	
	always_comb begin
		case(ps)
			IDLE: begin ns = (makeBreak)?((outCode == 8'h1D)?UP:(outCode == 8'h1C)?LP:(outCode == 8'h1B)?DP:(outCode == 8'h23)?RP:IDLE):IDLE;
							directionCommand = 4'b0000;
					end
			LP: begin ns = (makeBreak)?((outCode == 8'h1D)?UP:(outCode == 8'h1C)?LP:(outCode == 8'h1B)?DP:(outCode == 8'h23)?RP:IDLE):LP;
							directionCommand = 4'b1000;
					end
			RP: begin ns = (makeBreak)?((outCode == 8'h1D)?UP:(outCode == 8'h1C)?LP:(outCode == 8'h1B)?DP:(outCode == 8'h23)?RP:IDLE):RP;
							directionCommand = 4'b0001;
					end
			UP: begin ns = (makeBreak)?((outCode == 8'h1D)?UP:(outCode == 8'h1C)?LP:(outCode == 8'h1B)?DP:(outCode == 8'h23)?RP:IDLE):UP;
							directionCommand = 4'b0100;
					end
			DP: begin ns = (makeBreak)?((outCode == 8'h1D)?UP:(outCode == 8'h1C)?LP:(outCode == 8'h1B)?DP:(outCode == 8'h23)?RP:IDLE):DP;
							directionCommand = 4'b0010;
					end
			default: begin ns = IDLE;
								directionCommand = 4'b0000;
						end
		endcase
	end
	
	always_ff@(posedge clk)begin
		if(reset)begin
			ps <= IDLE;
		end else begin
			ps <= ns;
		end
	end
	
endmodule 


module keyboardTranslate_testbench();
	logic clk, reset, valid, makeBreak;
	logic [7:0] outCode;
	logic [3:0] directionCommand;
	
	keyboardTranslate dut(.clk, .reset, .valid, .makeBreak, .outCode, .directionCommand);
	
	parameter clock_period = 100;
		
	initial begin
		clk <= 0;
		forever #(clock_period /2) clk <= ~clk;
	end //initial
	
	initial begin
		reset <= 1; valid <= 0; makeBreak <= 0;	outCode <= 0;      							@(posedge clk);
		reset <= 0;													@(posedge clk);
															@(posedge clk);
															@(posedge clk);
															@(posedge clk);
						outCode <= 8'h1D;									@(posedge clk);
															@(posedge clk);
															@(posedge clk);
															@(posedge clk);
															@(posedge clk);
		$stop;
	end
endmodule 